### PR TITLE
Bigtable: fix rendering of instance admin snippets.

### LINKED ISSUE #7522: Bigtable: docs Snippet only includes half of documentation
Small problem with `snippets_table.py` for `google.cloud.bigtable.row.DirectRow.clear` [documentation](https://googleapis.github.io/google-cloud-python/latest/bigtable/row.html#google.cloud.bigtable.row.DirectRow.clear) only showing half the example code (e.g. not actually showing the running of the clear command)

Screenshot from 2019-03-16 10-42-40

This is because the test has two parts and the snippit is only including the first. 

```
def test_bigtable_row_clear():
    # [START bigtable_row_clear]
    from google.cloud.bigtable import Client

    client = Client(admin=True)
    instance = client.instance(INSTANCE_ID)
    table = instance.table(TABLE_ID)

    row_key = b"row_key_1"
    row_obj = table.row(row_key)
    row_obj.set_cell(COLUMN_FAMILY_ID, COL_NAME1, b"cell-val")
    # [END bigtable_row_clear]

    mutation_size = row_obj.get_mutations_size()
    assert mutation_size > 0

    # [START bigtable_row_clear]
    row_obj.clear()
    # [END bigtable_row_clear]

    mutation_size = row_obj.get_mutations_size()
    assert mutation_size == 0
```

### PR DESCRIPTION
**Pull request by sangramql**
Closes #7522.

### CODE REVIEW

**Comment by sangramql** [comment]
@crwilcox @AVaksman @sduskis 
Please review the code.

**Comment by tseaver** [comment]
@sangramql I can't see the failed Kokoro log, but @busunkim96 reports that it is:

```
Running session lint
Creating virtualenv using python3.7 in /tmpfs/src/github/google-cloud-python/bigtable/.nox/lint
pip install flake8 black ../api_core ../core
black --check google tests docs
 would reformat /tmpfs/src/github/google-cloud-python/bigtable/docs/snippets.py
All done! 💥 💔 💥
1 file would be reformatted, 72 files would be left unchanged.
Command black --check google tests docs failed with exit code 1 Session lint failed.
```

Can you please run `nox -re blacken`, commit, and push?

**Comment by sangramql** [comment]
nox -re blacken is working fine on my machine.
I also added 3.7 check.
@nox.session(python=["3.6","3.7"])
def blacken(session):
    """Run black.

--------------cmd--------------
MacBook-Pro:bigtable sqa$ nox -re blacken
nox > Running session blacken-3.6
nox > Re-using existing virtualenv at /Users/sqa/Documents/GitHub/google-cloud-python/bigtable/.nox/blacken-3-6.
nox > pip install --upgrade black
nox > black google tests docs
All done! ✨ 🍰 ✨
73 files left unchanged.
nox > Session blacken-3.6 was successful.
nox > Running session blacken-3.7
nox > Re-using existing virtualenv at /Users/sqa/Documents/GitHub/google-cloud-python/bigtable/.nox/blacken-3-7.
nox > pip install --upgrade black
nox > black google tests docs
All done! ✨ 🍰 ✨
73 files left unchanged.
nox > Session blacken-3.7 was successful.
nox > Ran multiple sessions:
nox > * blacken-3.6: success
nox > * blacken-3.7: success

**Comment by tseaver** [comment]
Ignoring spurious `pubsub` / `logging` / `storage` failures.

**Pull request merged**
