### PR TITLE
Removed stale proto file

### PR DESCRIPTION
**Pull request by kitokirti**
Removed stale proto file

### CODE REVIEW

**Comment by kitokirti** [comment]
Hi @parthea , I will look into it.

**Comment by kitokirti** [comment]
Hi @parthea , we have signed the CLA and rescanned the PR, but still it shows that the CLA has not been signed. Could you please look into.

**Comment by parthea** [comment]
Please could you check if the email listed at [this link](
https://patch-diff.githubusercontent.com/raw/googleapis/google-cloud-python/pull/12230.patch) is the same as the email address associated with a CLA? If not, we'll need to change the git author email to be the same one that is covered by the CLA. If the email address is correct, there could be a 24-48 hour delay before the update appears in Github.

Please also check that the email associated with the CLA is also added to your Github account.

**Comment by kitokirti** [comment]
Hi @parthea , i have checked all the conditions and waited for more that 48 hours but still the CLA fails.

**Comment by parthea** [comment]
@kitokirti,

Please see the troubleshooting section here:
https://opensource.google/documentation/reference/cla#troubleshoot

I've also reached out to an internal team to help troubleshoot the CLA check. (Googlers see b/323847466)

**Comment by parthea** [comment]
Hi @kitokirti,
I apologize for the delay. The next step is to go through https://cla.developers.google.com to execute the CLA or reach out to the email address listed on the about page here: https://cla.developers.google.com/about (cla-submissions at google com)

**Comment by parthea** [comment]
Hi @kitokirti,

I'm going to close this PR but please feel free to open it once the process at https://cla.developers.google.com has been completed

**Pull request closed without merging**
