### PR TITLE
PubSub: Add an option to streaming pull to invoke callbacks for batches of messages

### LINKED ISSUE #4994: pubsub API: allow registering a callback for batches of messages
The old API allowed you to operate on batches of messages. Sometimes, this is advantageous as you can aggregate other calls. With the current API, this is non trivial.

So, I think (if the underlying code supports it), adding, either a parameter to open(), or another function open_many() that'll always return a list (there could be a limit in the flow control), even if it's just with one item would be useful.

### PR DESCRIPTION
**Pull request by plamut**
Closes #4994.

---
## Do not merge yet!
This has been removed from GA for now ([comment](https://github.com/googleapis/google-cloud-python/issues/4994#issuecomment-493485665)), because other implementations currently do not have this feature.

---

This PR adds an option to receive asynchronously pulled messages in callbacks in batches, rather than a single message per each callback invocation.

> NOTE: This PR branch is based on #7948, because it needs to modify several parts of the code added by the latter.

### How to test

**Steps to reproduce:**
- Prerequsite: Have a working service account, pubsub topic, and subscription created.
- Rapidly publish several messages to the topic - they must be sent to the PubSub server in the same batch (or several batches)
- Create a subscriber client and start the streaming pull with the argument `batch=True`:
```py
subscriber.subscribe(SUBSCRIPTION_NAME, callback, batch=True)
```

**Actual result (before the fix):**
The provided `callback` is invoked once for each message.

**Expected result (after the fix):**
The provided `callback` is invoked **once for each batch** of published message (subject to `FlowControl.max_messages` limits). The callback is invoked with a _list_ of messages as the argument.

### TODO list
- [x] Fix docs (format of some of the changed docstrings).

### CODE REVIEW

**Comment by sduskis** [comment]
`google/cloud/pubsub_v1/subscriber/client.py:202:15: W291 trailing whitespace`

**Comment by sduskis** [comment]
We should discuss this feature with the Pub/Sub team before merging.  They want to limit the difference between implementations in different languages, if possible.

**Comment by c0rvax** [comment]
Hi, is there any ETA of merging this? That is a pretty vital decision i have to make in project. And the decision depends of this ETA. Thanks!

**Comment by plamut** [comment]
@c0rvax I can only give an unofficial answer, as I am not the decision maker here, but AFAIK this PR is unlikely to be merged in the near future.

PubSub clients for other languages currently lack this feature, and consistency is desired across various implementations.

**Comment by c0rvax** [comment]
@plamut 

Thanks for your answer, it helps a lot!

**Comment by szeitlin** [comment]
It would be nice to have this feature, though, since java, ruby and go all have the streaming pull/concurrency feature, and python does not.

**Comment by plamut** [comment]
@szeitlin The Python client also supports asynchronous (streaming) pull, and it's actually the preferred way of pulling the messages ([docs](https://cloud.google.com/pubsub/docs/pull#asynchronous-pull)). The thing here is just that each received message is dispatched individually, i.e. one message per each callback invocation, as opposed to multiple messages per invocation.

Or did I misunderstand your comment?

**Comment by szeitlin** [comment]
We're trying the asynchronous approach, but ultimately we still have a use case where we'll need to write out messages in batch, which is going to be a bit of work to implement using the streaming pull method and checking to see when we've accumulated enough messages. I get the impression a few other people would appreciate this feature for the same reason, unless I'm misunderstanding how it's supposed to work?

**Comment by plamut** [comment]
The batch callback, at least how it was implemented here, simply means that if N messages are available to dispatch to the user callback, all of them are passed to the callback in a list, as opposed to N callback invocations, one for each individual message.

The concern raised in internal discussions was that it is not defined what a "batch" actually is, and can thus be confusing to users. Publishing several messages in a single batch does not necessarily mean that the backend will actually deliver these messages in a single batch. The "received" batch can also contain messages from several different publish batches.

Since the number of messages received in a single batch might vary, you would still have to implement the aggregation logic to know when enough messages have been accumulated.

Just to avoid any misunderstanding, what would be your expectation of such feature, i.e. what messages would you expect to receive in a particular batch?

**Comment by szeitlin** [comment]
Good question. I guess we were just hoping we could set a minimum batch size (in our case it's ok if things arrive out of order).

**Comment by plamut** [comment]
The backend does not support that, unfortunately, thus any "minimum size" batching logic needs to be implemented on the client side. While the client library could do that internally, it cannot decide for the user what to do in edge cases, e.g. when no new messages arrive for a substantial period of time, but it does not yet hold enough messages to release the next batch.

One way to achieve batching is to put received messages into a queue which is then processed by a different thread that can then batch/process them as needed, e.g. write them out when there are enough of them in the queue.

```py
import queue

received_queue = queue.Queue()

...

future = subscriber.subscribe("my/subscription/path", callback=received_queue.put)

try:
    future.result()
except KeyboardInterrupt:
    future.cancel()
```

Would that help?

**Comment by szeitlin** [comment]
This is an interesting point, we will try that if the way we have it isn't fast enough. Thanks!

**Pull request closed without merging**
