### PR TITLE
NDB: First pass at porting metadata module

### PR DESCRIPTION
**Pull request by cguardia**
All classes and their methods have been ported, but there are a few module level methods that can't be ported at this time, because they depend on code that has not been ported yet from other modules.

### CODE REVIEW

**Comment by chrisrossi** [comment]
Is there any way you could rebase this on master? That'll make it easier to see what's new for this PR.

**Comment by cguardia** [comment]
@chrisrossi I can rebase, but I'm not sure how to get that done with this setup. DO I just run `git rebase master`, then push the result to this branch?

**Comment by chrisrossi** [comment]
> @chrisrossi I can rebase, but I'm not sure how to get that done with this setup. DO I just run `git rebase master`, then push the result to this branch?

Yes. You'll need ``-f`` with the ``git push``.

**Comment by cguardia** [comment]
Done.

**Pull request merged**
