### PR TITLE
NDB: port stats module from old ndb code

### PR DESCRIPTION
**Pull request by cguardia**
Ported the whole module, with unit tests. Wanted to add system tests, but it seems we need more functionality before that can be done.

### CODE REVIEW

**Comment by cguardia** [comment]
@chrisrossi about the comment in the code, do you know where the code that would supposedly use these classes resides? Same thing happens with metadata.

**Comment by chrisrossi** [comment]
> @chrisrossi about the comment in the code, do you know where the code that would supposedly use these classes resides? Same thing happens with metadata.

I think this is it. These are model classes that reflect entities that Datastore creates automatically. (Or, at least, the GAE version.) I'd say you could construct a ``Key`` to ``get`` one of these, but I don't know how we'd know an ``id`` or ``name`` to use to construct the key. Unless you have some insight there, we may have to wait until we have a queries, then you'd just run a query on the ``kind`` of stat you're interested in. 

You should be able to explore what Google Cloud Datastore currently provides using ``google.cloud.datastore`` and running some queries. That's my theory, anyway.

**Comment by cguardia** [comment]
@chrisrossi Thanks. I did run some queries with datastore when I was looking at this first. At the very least, it does provide these stats and uses the same names, so I think it's safe to assume that it still works like that. We'll need to wait for query for further action.

**Comment by chrisrossi** [comment]
Notice that ``nox -e docs`` seems to be failing Kokoro.

**Comment by cguardia** [comment]
Fixed. Sorry about that.

**Comment by chrisrossi** [comment]
Great. Google is having us merge our own branches. Merge at your convenience.

Since we're working in a mono repo, I like to start all my squashed commit messages with "NDB: " at merge time, so it's obvious which API the commit is for.

**Comment by chrisrossi** [comment]
You can merge this. We generally use "Squash and merge" to get each PR down to a single commit in master.

**Comment by cguardia** [comment]
Hmmm, I did the command line merge last week, using --squash. Will try the button.

**Comment by chrisrossi** [comment]
Is it possible you merged it cguardia and not google-cloud-python?

**Comment by cguardia** [comment]
I think not, but I'm not sure. Will use the button from now on. Thanks.

**Comment by chrisrossi** [comment]
Sorry, I just assumed that since the PR was still open, it was unmerged. It just occurred to me that if you squash, then github can't automatically detect if the branch was merged. Looks like it's in there twice, now. 

But, yes, if you use the button then it definitely knows it's merged.

Thanks.

**Pull request merged**
