### PR TITLE
Bigtable: Split bigtable snippets

### PR DESCRIPTION
**Pull request by sangramql**

### CODE REVIEW

**Comment by sangramql** [comment]
@tseaver, @AVaksman, Please review the code, this is same code of snippets but just split into different files.

**Comment by sduskis** [comment]
@sangramql, please see #6339. Please incorporate those changes into this PR.

**Comment by sangramql** [comment]
> @sangramql, please see #6339. Please incorporate those changes into this PR.

Yes, will fix the code accordingly. Thank you for the fix.

**Comment by sangramql** [comment]
> @sangramql, please see #6339. Please incorporate those changes into this PR.

@sduskis , can we have some other assert inplace of 
"assert len(policy_latest.bigtable_viewers) is not 0"? So that test would pass. 
And also lint is failing due to unused variable policy_latest.

**Comment by tseaver** [comment]
I'd actually prefer to see the snippets stay in a single file, with only a single global setup / teardown.

**Comment by tseaver** [comment]
Also, please see my fix for the IAM policy snippets in #6343.

**Comment by sangramql** [comment]
> Also, please see my fix for the IAM policy snippets in #6343.

Thank you for the fix.

**Comment by sangramql** [comment]
> I'd actually prefer to see the snippets stay in a single file, with only a single global setup / teardown.

ok. 
@sduskis @AVaksman , just fyi.

**Comment by tseaver** [comment]
I don't want to replicate all the setup / teardown code across different snippets files, nor work out how to get them running "cleanly" under `nox`.

**Pull request closed without merging**
