### PR TITLE
Logging: Fix tests.

### PR DESCRIPTION
**Pull request by busunkim96**
Fixes internal issue 134713268.

### CODE REVIEW

**Comment by bmccutchon** [comment]
I think you need to also change the usage to `datetime.datetime.utcfromtimestamp` to fix the build.

**Comment by tseaver** [comment]
Also, we need to figure out why #8227 passed CI here.

**Comment by busunkim96** [comment]
@tseaver We forgot to add `kokoro: force-run` on that PR.

**Comment by busunkim96** [comment]
Looks like there's some more work to get tests passing again (after fixing the import)

```
self = <google.cloud.logging.handlers.transports.background_thread._Worker object at 0x7f48d3fd15f8>

    def _thread_main(self):
        """The entry point for the worker thread.
    
        Pulls pending log entries off the queue and writes them in batches to
        the Cloud Logger.
        """
        _LOGGER.debug("Background thread started.")
    
        done = False
        while not done:
            batch = self._cloud_logger.batch()
            items = _get_many(
                self._queue,
                max_items=self._max_batch_size,
                max_latency=self._max_latency,
            )
    
            for item in items:
                if item is _WORKER_TERMINATOR:
                    done = True  # Continue processing items.
                else:
>                   batch.log_struct(**item)
E                   TypeError: log_struct() got an unexpected keyword argument 'timestamp'

google/cloud/logging/handlers/transports/background_thread.py:148: TypeError

```

**Comment by tseaver** [comment]
I don't understand the `TypeError`.  `Batch.log_struct` is a straightforward wrapper: https://github.com/googleapis/google-cloud-python/blob/c5acdad71bbbc1d58b8e6e5f0a749660823a88b3/logging/google/cloud/logging/logger.py#L338-L348

creating a `StructEntry` https://github.com/googleapis/google-cloud-python/blob/c5acdad71bbbc1d58b8e6e5f0a749660823a88b3/logging/google/cloud/logging/entries.py#L295

which derives from `LogEntry`: https://github.com/googleapis/google-cloud-python/blob/c5acdad71bbbc1d58b8e6e5f0a749660823a88b3/logging/google/cloud/logging/entries.py#L147

which derives from `_LogEntryTuple`: https://github.com/googleapis/google-cloud-python/blob/c5acdad71bbbc1d58b8e6e5f0a749660823a88b3/logging/google/cloud/logging/entries.py#L67-L87

which clearly takes a `timestamp`.

**Comment by tseaver** [comment]
OK, the `batch` in this case is a hand-rolled mock: https://github.com/googleapis/google-cloud-python/blob/c5acdad71bbbc1d58b8e6e5f0a749660823a88b3/logging/tests/unit/handlers/transports/test_background_thread.py#L420-L446

There will also be test failures due to the use of a `mock.Mock` passed to `_Worker.enqueue`:

```python

    def enqueue(
        self, record, message, resource=None, labels=None, trace=None, span_id=None
    ):
        """Queues a log entry to be written by the background thread.
    
        :type record: :class:`logging.LogRecord`
        :param record: Python log record that the handler was called with.
    
        :type message: str
        :param message: The message from the ``LogRecord`` after being
                        formatted by the associated log formatters.
    
        :type resource: :class:`~google.cloud.logging.resource.Resource`
        :param resource: (Optional) Monitored resource of the entry
    
        :type labels: dict
        :param labels: (Optional) Mapping of labels for the entry.
    
        :type trace: str
        :param trace: (optional) traceid to apply to the logging entry.
    
        :type span_id: str
        :param span_id: (optional) span_id within the trace for the log entry.
                        Specify the trace parameter if span_id is set.
        """
        self._queue.put_nowait(
            {
                "info": {"message": message, "python_logger": record.name},
                "severity": record.levelname,
                "resource": resource,
                "labels": labels,
                "trace": trace,
                "span_id": span_id,
>               "timestamp": datetime.datetime.utcfromtimestamp(record.created),
            }
        )
E       TypeError: an integer is required (got type Mock)
```

**Comment by bmccutchon** [comment]
If this is going to take a long time to fix, would it make sense to roll back PR #8227 in the meantime?

**Comment by tseaver** [comment]
- Monitoring and Webrisk fail due to Kokoro-internal error: "Cannot check out non-mergeable pull request as if merged."
- Firestore fails due to #7130.
- Spanner fails due to #7504.

**Pull request merged**
