### PR TITLE
docs: add python 2 EOL warning to reference documentation

### PR DESCRIPTION
**Pull request by busunkim96**
This PR adds a banner like the one below for all libraries:

Cloud Asset Python 2 Deprecation and EOL

### CODE REVIEW

**Comment by crwilcox** [comment]
We can link to https://cloud.google.com/python/docs/python2-sunset/

**Comment by busunkim96** [comment]
Working on getting this added to the enerator

**Comment by busunkim96** [comment]
Asset - system test failure (VPCSC)
BigQuery - system test failure (fixed in #9649) 
Resource Manager - needs blackening
Security Center - snippets failure (resource names too long)
Storage - most likely a flake, failed only in 2.7
Trace - system test failure (VPCSC)

**Comment by tseaver** [comment]
The current `storage` failure is an actual buggy unit test (query string parameter ordering):

```python
E   Expected: request(data=<ANY>, headers=<ANY>, method='POST', url='https://storage.googleapis.com/storage/v1/b?project=OTHER_PROJECT&userProject=USER_PROJECT')
E   Actual: request(data='{"name": "bucket-name"}', headers={'Content-Type': 'application/json', 'X-Goog-API-Client': 'gcloud-python/1.22.0  gl-python/3.5.3 gax/1.14.3 gccl/1.22.0', 'User-Agent': 'gcloud-python/1.22.0  gl-python/3.5.3 gax/1.14.3 gccl/1.22.0', 'Accept-Encoding': 'gzip'}, method='POST', url='https://storage.googleapis.com/storage/v1/b?userProject=USER_PROJECT&project=OTHER_PROJECT')
```

Reported as #9714.

**Comment by busunkim96** [comment]
Merging as remaining errors are being addressed in open PRs and are unrelated to the docs change

**Pull request merged**
