### PR TITLE
API Core / BigQuery Storage: Fix pins of 'googleapis-common-protos.

### PR DESCRIPTION
**Pull request by tseaver**
Toward #8686.

### CODE REVIEW

**Comment by tswast** [comment]
`E   ModuleNotFoundError: No module named '_bz2'`

There's a good chance this was caused by a bad wheel for pyarrow. We might need to pin to pyarrow 0.13.0 for now.

**Comment by tseaver** [comment]
@tswast `bz2` is part of the standard library:  I think there has been breakage in the docker images (no installing `libbz2-dev` before building Python from source).

**Comment by busunkim96** [comment]
I moved 'latest' back to an older build from March and got the same error :woman_shrugging: Rebuilding and republishing the image right now.

**Comment by busunkim96** [comment]
Please hold off on merging. The latest test run skipped a bunch of sessions: https://g3c.corp.google.com/results/invocations;query=target/07a1a87e-228d-4d99-9281-2682932d1b3e/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-python%2Fpresubmit%2Fbigquery_storage/log

**Comment by tseaver** [comment]
@busunkim96 They look green to me now.  The two which are not no-ops both succeeded:

- [API Core](https://source.cloud.google.com/results/invocations/266f18d3-50ae-438f-86f9-9571caeabc9d/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-python%2Fpresubmit%2Fapi_core/log)
- [BigQuery Storage](https://source.cloud.google.com/results/invocations/07a1a87e-228d-4d99-9281-2682932d1b3e/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-python%2Fpresubmit%2Fbigquery_storage/log)

**Pull request merged**
