### PR TITLE
Language: Fix reference to EncodingType

### PR DESCRIPTION
**Pull request by mik-laj**
Hello,

The reference to this class is not correct. This PR introduces the correct reference.

Thanks

### CODE REVIEW

**Comment by tseaver** [comment]
Thanks for the patch, @mik-laj.

**Comment by tseaver** [comment]
Kokoro failures in unrelated API clients are due to a Kokoro-internal glitch, "Cannot check out non-mergeable pull request as if merged."

**Comment by mik-laj** [comment]
I have more similar errors.  I will try to fix soon.

**Comment by mik-laj** [comment]
For example:
In https://googleapis.github.io/google-cloud-python/latest/language/gapic/v1/api.html#google.cloud.language_v1.LanguageServiceClient.annotate_text 
Features is missing.

**Comment by tseaver** [comment]
Ugh, this PR touches generated code direclty, rather than via `synth.py`, which means that our auto-synth bot will try daily to undo the change (see PR #8794).

**Comment by mik-laj** [comment]
Is the entire process of creating these libraries described? I would like to know more about this project. I work a lot with these libraries and I have many comments on how they work, but I do not know how to report issues. When I or someone from my team reports errors, we are sent back to other projects.

**Comment by tseaver** [comment]
@mik-laj The "generated" parts of our libraries use the engine from https://github.com/googleapis/synthtool, under the control of the `synth.py` script in each client library directory. To run a synth generation:

```bash
$ cd language/
$ /path/to/venv/bin/synthtool
...
synthtool > Wrote metadata to synth.metadata.
```

The `yoshi-automation` bot runs synth jobs for each client library daily, and posts PRs if any changes result (other than to the `synth.metadata` file).

We should likely document the synth process in `CONTRIBUTING.rst`.

**Comment by mik-laj** [comment]
What is the role of the gapic-generator?

**Comment by tseaver** [comment]
> What is the role of the gapic-generator?

`synthtool` pulls a docker image which contains (among other things) the `gapic-generatore` software, and uses it to generate the code (as specified in `synth.py`).

**Pull request merged**
