### PR TITLE
Release storage 1.13.0

### PR DESCRIPTION
**Pull request by tseaver**
This pull request was generated using releasetool.

### CODE REVIEW

**Comment by frankyn** [comment]
Thanks @tseaver!

**Comment by tseaver** [comment]
Merging w/o actual review because of permission issues (@frankyn lost the reviewer role when we migrated from `/GoogleCloudPlatform` to `/googleapis`).

**Comment by tseaver** [comment]
Release is at https://github.com/googleapis/google-cloud-python/releases/tag/storage-1.13.0

**Comment by tseaver** [comment]
Release artifacts [available on PyPI](https://pypi.org/project/google-cloud-storage/1.13.0/).

**Pull request merged**
