### PR TITLE
Firestore: Treat 'None' as EOF in 'Watch.on_snapshot'.

### PR DESCRIPTION
**Pull request by tseaver**
See:
https://github.com/googleapis/google-cloud-python/pull/8650#pullrequestreview-261830931

### CODE REVIEW

**Comment by plamut** [comment]
Something weird is going on, I removed and re-added the force run label, the label is there, but there is no record of that on the PR timeline, and the `yoshi-kokoro` bot does not see it.

**Comment by crwilcox** [comment]
I cleaned out firestore to see if that helps. forcing a ci run.

**Comment by tseaver** [comment]
The Kokoro jobs for Bigtable and Natural Language both fail due to a Kokoro-internal glitch:

> Cannot check out non-mergeable pull request as if merged.

**Comment by plamut** [comment]
@tseaver Is there anything we can do to get around the glitch?

**Comment by tseaver** [comment]
@plamut 

> Is there anything we can do to get around the glitch?

I'm actually worried that there is something more sinister at play.

@crwilcox Can you double-check that the clean-out really worked in the CI project?  E.g.:

```python
documents = []
for collection in client.collections():
    documents.extend(collection.list_documents()
assert len(documents) == 0
```

**Comment by tseaver** [comment]
I have added a commit to make the system test output verbose, so that we can figure out which test is hanging.

**Comment by tseaver** [comment]
@crwilcox I'm expecting this Kokoro run to time out again:  can you post the hung systest output when it does?  Or maybe you have the keys to see the output even before it times out?

**Pull request merged**
