### PR TITLE
Firestore models

### PR DESCRIPTION
**Pull request by Billcountry**
> Question: https://github.com/googleapis/google-cloud-python/pull/8739#issuecomment-514595342

This PR introduces firestore models and is inspired by `db` and `ndb` models available in app engine standard. It's main aim is to enable operations such as:
```py
from google.appengine.ext import db

class User(db.Model):
    name = db.TextField()
```
since google is starting to market firestore as the datastore replacement, I decided to write a `db` module that provides similar functionality for firestore. However this didn't go without complications where in firestore a document can actually hold a collection
But I managed to overcome this where a model can now be a child of an instance of another model and this relationship enforced.
```py
"""
This code creates a model with some possible scenarios when working with db.FirestoreModel

It assumes a case where a company offers SAAS to different enterprises for a chat system
- A user can belong to multiple enterprises
- All enterprises have Clients and Clients have messages
"""

from google.cloud.firestore_v1beta1 import db


class User(db.FirestoreModel):
    user_name = db.StringField(length=16, required=True)
    email_address = db.StringField(required=True)
    full_name = db.StringField(required=True)
    password = db.StringField(required=False)
    date_registered = db.DateTimeField(default=db.SERVER_TIMESTAMP)
    __sub_collection__ = "user_data"


class Enterprise(db.FirestoreModel):
    name = db.StringField(required=True)
    logo = db.BytesField()

    def create_account(self, user, roles=[]):
        account = Accounts(__parent__=self, user=user, roles=roles)
        account.put()


class Accounts(db.FirestoreModel):
    user = db.ReferenceField(User)
    roles = db.ListField(field_type=db.StringField())
    date_added = db.DateTimeField(auto_add_now=True)
    last_updated = db.DateTimeField(auto_now=True)


class Clients(db.FirestoreModel):
    __sub_collection__ = Enterprise
    email_address = db.StringField()
    name = db.StringField()


class Fields(db.FirestoreModel):
    __sub_collection__ = Clients
    field_type = db.StringField("string")
    value = db.StringField()


class Messages(db.FirestoreModel):
    __sub_collection__ = Enterprise
    client = db.ReferenceField(Clients, required=True)
    sender = db.ReferenceField(Accounts)
    message_date = db.DateTimeField(auto_add_now=True)
```

### CODE REVIEW

**Comment by Billcountry** [comment]
I have a pending question before proceeding with the completion of this project. The models seems to have been removed from all the libraries including datastore in this project. Wondering if there's a strategical reason for that which renders this piece of work irrelevant?

**Comment by tseaver** [comment]
@Billcountry 

> The models seems to have been removed from all the libraries including datastore in this project.

`google-cloud-datastore` itself never had a "models" concept.  The re-implementation of the GAE `ndb` module is being done in a [separate repository]https://github.com/googleapis/python-ndb/).

**Comment by Billcountry** [comment]
@tseaver 
 
> > The models seems to have been removed from all the libraries including datastore in this project.
> 
> `google-cloud-datastore` itself never had a "models" concept. The re-implementation of the GAE `ndb` module is being done in a [separate repository]https://github.com/googleapis/python-ndb/).

In this case would you advise on closing of this and implementing the module separately for `firestore`?

**Comment by tseaver** [comment]
> Would you advise on closing of this and implementing the module separately for firestore?

My guess is that `python-ndb` will subsume this whole effort. Summoning @cguardia, @chrisrossi, @andrewsg, who are the drivers for the `python-ndb` project.

**Comment by andrewsg** [comment]
Tthe goal of the ndb project is explicitly to facilitate migration from the Google App Engine python27 runtime to new platforms and runtimes. The target audience is only existing GAE python27 ndb users, though of course we won't stop other people from using it. We have a strict commitment not to add any new features or support Firestore native mode in the future.

If this PR is intended to facilitate migration from GAE, it's probably overlapping with the new NDB project. If it's just to add models to the Firestore client library project because that is a desired feature, then perhaps it's not overlapping after all.

**Comment by Billcountry** [comment]
Thanks guys for the feedback @andrewsg @tseaver 
Closing this

**Pull request closed without merging**
