### PR TITLE
Initial Generation of reCAPTCHA Enterprise.

### PR DESCRIPTION
**Pull request by busunkim96**

### CODE REVIEW

**Comment by busunkim96** [comment]
Waiting for Kokoro configs to be merged for reCAPTCHA Enterprise.

**Comment by tseaver** [comment]
Is it too late to ask for a renaming here to `recaptcha_enterprise`?

**Comment by busunkim96** [comment]
@tseaver Will do. I would like the package to be named `google-cloud-recaptcha-enterprise` to match what other languages did, so that is probably a better fit.

**Comment by tseaver** [comment]
Docs build fails on CircleCI with:

```
nox > Command pip install --upgrade -r docs/requirements.txt failed with exit code 1:
ERROR: recaptchaenterprise/ should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
```

PR needs to update `docs/requirements.txt` to match the rename.

**Comment by tseaver** [comment]
[Bigtable failure](https://source.cloud.google.com/results/invocations/cbb03403-3f31-47b5-b292-867ec76241ab/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-python%2Fpresubmit%2Fbigtable/log) was due to resource exhaustion (leaked instances from snippets), which should be fixed now.

**Comment by tseaver** [comment]
Does the Kokoro config need to be changed to match the rename?

**Comment by busunkim96** [comment]
Yes! I'm waiting on internal PRs for the rename and the Kokoro config.

*From: *Tres Seaver <notifications@github.com>
*Date: *Tue, May 7, 2019 at 8:03 AM
*To: *googleapis/google-cloud-python
*Cc: *Bu Sun Kim, Author

Does the Kokoro config need to be changed to match the rename?

**Comment by tseaver** [comment]
@busunkim96 Is this effort dead?

**Comment by busunkim96** [comment]
Yep this is dead (for now). The team didn't get back to us about some changes we asked for. Closing the PR.

**Pull request closed without merging**
