### PR TITLE
refactor(bigquery): update code samples of load table autodetect and truncate

### PR DESCRIPTION
**Pull request by HemangChothani**
Towards #8989 

### List of changes:

1. load_table_uri_autodetect_csv 
2. load_table_uri_autodetect_json
3. load_table_uri_truncate_avro.py
4. load_table_uri_truncate_json.py
5. load_table_uri_truncate_csv.py
6. load_table_uri_truncate_orc.py
7. load_table_uri_truncate_parquet.py

### CODE REVIEW

**Comment by plamut** [comment]
(not a complete review in any way, just a remark)

Shouldn't the copyright notice contain the year 2020 in new files?

**Comment by HemangChothani** [comment]
test_client_load_partitioned_table snippet failed is unrelated to changes.

**Comment by plamut** [comment]
The failing snippet test is fixed in #10195.

**Comment by plamut** [comment]
Starting the repo split, please do not merge.

**Comment by plamut** [comment]
The repo split for BigQuery is done, please re-open the PR in the new repo, thanks!

https://github.com/googleapis/python-bigquery

**Comment by plamut** [comment]
Superseded by https://github.com/googleapis/python-bigquery/pull/28

**Pull request closed without merging**
