### PR TITLE
Docs: Add compatibility check badges to READMEs.

### PR DESCRIPTION
**Pull request by ylil93**
Hello google package maintainers,
The badges being added to the READMEs in this PR will indicate each package's compatibility with other google packages. This addresses a set of user bugs which have happened when a user depends on two Cloud libraries (or runtimes that bundle libraries), say A and B, which both depend on library C. If the two libraries require different versions of C, the users can run into issues both when they pip install the libraries, and when they deploy their code. Our compatibility server checks that all libraries we make including these ones are self and pairwise compatible as well as not having any deprecated dependencies. The two badges being added to each README will mark the build for your project green when the latest version available on PyPI and github HEAD respectively meet all compatibility checks with itself and all other libraries. The badge target will link to a details page that elaborates on the current status. This should help you fix issues pre-release, to avoid user surprises. For more information, please take a look at our project charter at go/python-cloud-dependencies-project-charter and the badging PRD https://docs.google.com/document/d/1GYRFrfUou2ssY71AtnLkc8Sg1SD4dxqN4GzlatGHHyI/edit?ts=5c6f031d

### CODE REVIEW

**Comment by tseaver** [comment]
@ylil93 Can you please link the public URL for project charter, and grant read access to it and the badging PRD?

**Comment by ylil93** [comment]
> @ylil93 Can you please link the public URL for project charter, and grant read access to it and the badging PRD?

Publicly accessible equivalents for the project charter and badge PRD, respectively, are the following:
https://github.com/GoogleCloudPlatform/cloud-opensource-python/blob/master/README.rst
https://github.com/GoogleCloudPlatform/cloud-opensource-python/blob/master/badge_server/README.rst

**Comment by busunkim96** [comment]
@tseaver Do you have more comments on this?

**Comment by tseaver** [comment]
Logging failure due to a new flaky systest, reported in #8676.

Firestore failure due to existing flaky systest, #7130.

Storage failure due to a puzzling Kokoro issue (unable to import the stdlib's `bz2` module).

Asset failure in the two VPCSC tests added in #8613 and updated in #8627.

**Comment by ylil93** [comment]
> Logging failure due to a new flaky systest, reported in #8676.
> 
> Firestore failure due to existing flaky systest, #7130.
> 
> Storage failure due to a puzzling Kokoro issue (unable to import the stdlib's `bz2` module).
> 
> Asset failure in the two VPCSC tests added in #8613 and updated in #8627.

I'm not sure what these mean... Could I have some clarification? From my point of view, this change only touches README files, so I don't see how it could be the cause of any of these breakages.

**Comment by tseaver** [comment]
@ylil93 

> I'm not sure what these mean... Could I have some clarification? From my point of view, this change only touches README files, so I don't see how it could be the cause of any of these breakages.

When reviewing a PR, we need to note the source of any CI failures, even those unrelated to the changes made by the PR.

**Comment by tseaver** [comment]
The CircleCI job actually completed successfully.

**Comment by tseaver** [comment]
@ylil93 Can you please explain the utility of the flags?  For instance, on the [`asset/README.rst` file](https://github.com/googleapis/google-cloud-python/tree/master/asset) I don't understand the errors for either the relesaed version or the master version.

**Comment by ylil93** [comment]
> @ylil93 Can you please explain the utility of the flags? For instance, on the [`asset/README.rst` file](https://github.com/googleapis/google-cloud-python/tree/master/asset) I don't understand the errors for either the relesaed version or the master version.

If you navigate to the badge target by clicking on it, you'll see an explanation for the incompatible status.

For PyPI, `asset` has an incompatibility with `grpc-google-iam-v1` because `google-cloud-asset` 0.2.0 has requirement `grpc-google-iam-v1`<0.12dev,>=0.11.4, but you have `grpc-google-iam-v1` 0.12.3. This is true for both py2 and py3.

In other words, `asset` requires <0.12dev,>=0.11.4 of `grpc-google-iam-v1`, but during the build,  0.12.3 was used, which resulted in the incompatibility status. It looks like for the current release, `asset` had somehow pinned both 0.12.3 and the range <0.12dev,>=0.11.4.

For the github badge, the repo is incompatible with several other google packages for similar reasons.

The flags you should care about are:
self incompatible (red) - pip error when installing the given package
incompatible (red) - pip error when installed with another package
obsolete dependency (red) - refer to the high priority items in [this](https://github.com/GoogleCloudPlatform/cloud-opensource-python/issues/53)
old dependency (yellow green) - refer to the low priority items in [this](https://github.com/GoogleCloudPlatform/cloud-opensource-python/issues/53)

**Pull request merged**
