### PR TITLE
Storage: add 'Client.create_hmac_key' method.

### PR DESCRIPTION
**Pull request by tseaver**
~~Uses #8041 as a base.~~

Toward #7851.

### CODE REVIEW

**Comment by tseaver** [comment]
Unrelated [spanner failure due to Kokoro-internal glitch](https://source.cloud.google.com/results/invocations/e53b0cae-d635-448e-94b2-4176c4785bbc/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-python%2Fpresubmit%2Fspanner).

**Comment by tseaver** [comment]
Rebased after merge of #8041 to the feature branch.

**Comment by tseaver** [comment]
@jkwlui This PR is ready for review.  If you'd rather work on a larger chunk, #8043 is based on this one:  you could close this one and review there.

**Comment by jkwlui** [comment]
Thank you @tseaver, I'll review #8043 as a whole.

**Comment by tseaver** [comment]
Per @jkwlui, closing in favor of follow-on #8043, which contains these commits.

**Pull request closed without merging**
