### PR TITLE
BigQuery Snippets: Use autodetected location

### PR DESCRIPTION
**Pull request by grant**
Remove location as it is now autodetected.
See bug b/116968956 .

### CODE REVIEW

**Comment by busunkim96** [comment]
Container Analysis and Grafeas are failing because those libraries have not yet been merged.

**Comment by grant** [comment]
I don't know why the tests are failing.
It is hard finding the error with this build setup.

After a few clicks, I think there's a stacktrace with an unrelated error:
```
[11:54:04][ERROR] Failed to get build config
com.google.devtools.kokoro.config.ConfigException: Couldn't find build configuration under /tmp/workspace/workspace/cloud-devrel/client-libraries/google-cloud-python/presubmit/containeranalysis/src/github/google-cloud-python/.kokoro/presubmit.
```

**Comment by busunkim96** [comment]
@grant Yep, ContainerAnalysis and Grafeas are pending in #8186 (they're failing since Kokoro configs have already been merged internally). You can ignore those test failures.

**Comment by grant** [comment]
How can we ignore the test failures if the tests are failing? Are we implying that we want to approve this PR before all checks are green?

**Comment by busunkim96** [comment]
Yes, as long as the tests for the relevant APIs are passing we can merge it. We realize that's not ideal, but it's our current process.

**Comment by grant** [comment]
@busunkim96 OK.
So BQ passes.
Merge?

**Comment by alixhami** [comment]
Important to note that nobody actually approved this PR.

**Comment by busunkim96** [comment]
@alixhami Sorry, that is my bad :woman_facepalming:. I assumed it had been reviewed. 

We're putting splitting this repo on the OKRs for the next quarter and will turn on stricter protections (required status checks, reviews, etc) at that point.

**Pull request merged**
