### PR TITLE
Release logging 1.8.0

### PR DESCRIPTION
**Pull request by theacodes**
This pull request was generated using releasetool.

### CODE REVIEW

**Comment by tseaver** [comment]
Hmm, I have two open pull requests for `logging/`, ready to review.  Would it be better to land them first?

**Comment by tseaver** [comment]
Note that #6081 (adding `logging/synth.py`) is blocked pending a `googleapis-common-protos` release w/ the new monitored resource types.

**Comment by theacodes** [comment]
We have dragged this release out for far too long and are blocking partner teams. The remaining PRs and adding Synthesis can wait for the next release.

**Comment by theacodes** [comment]
Release is at https://github.com/googleapis/google-cloud-python/releases/tag/logging-1.8.0

**Pull request merged**
