### PR TITLE
Spanner: Test return empty array struct

### PR DESCRIPTION
**Pull request by chemelnucfin**

### CODE REVIEW

**Comment by tseaver** [comment]
No system test required (marked "unit").

**Comment by tseaver** [comment]
No longer marked "unit" in the current spreadsheet. :(

**Comment by tseaver** [comment]
@crwilcox If you can flip the CLA flag, I think this is ready to merge.

**Comment by chemelnucfin** [comment]
I'm ok

**Comment by tseaver** [comment]
@crwilcox, @theacodes Can one of you please flip the CLA flag?

**Pull request merged**
