### PR TITLE
Update Natural Language service name

### PR DESCRIPTION
**Pull request by mik-laj**
Hello,
It is recommended to use the full name of the service.
Greetings,
Kamil

Reference: https://github.com/apache/airflow/pull/4980#discussion_r270601531
CC: @wwlian

### CODE REVIEW

**Comment by tseaver** [comment]
@mik-laj Thanks for the patch!  We've had several push-and-pulls in how API branding is done, and so I'm relctant to just merge it.

@sduskis  Can you comment, or merge if this looks good to you?

**Comment by crwilcox** [comment]
I am also hesitant about this. We are pretty consistent in calling this language. Though, it isn't a big deal. In the readme for language (where go from this) we refer to it as `Python Client for Google Cloud Natural Language`

Also, should we sort this index? It is close to sorted now :)

**Comment by busunkim96** [comment]
"Natural Language" is what the product documentation uses. https://cloud.google.com/natural-language/

**Comment by sduskis** [comment]
@beccasaurus, do you have any input on this change?

**Comment by beccasaurus** [comment]
Wherever the product name is used, I would expect it to be "Natural Language" or "Natural Language API".

"Language" is OK when referring to a service object / namespace / something in the client library which is named `Language`.

**Comment by tseaver** [comment]
@crwilcox, @sduskis It worked out OK this time, but the full CI was not run on this PR, because @mik-laj is not a team member.

**Comment by mik-laj** [comment]
@crwilcox Thanks for merge.

**Pull request merged**
