### PR TITLE
docs(bigquery): update existing code samples

### PR DESCRIPTION
**Pull request by Emar-Kar**
List of changes:
-
1. **browse_table_data**:
   - add a description of how to print row data in tabular format. (as it was before).
2. **All files**
   - add `API request`, `Must match the destination dataset location` and `Waits for the job to complete` comments.
3. **get_routine**:
   - change `whitespaces` in prints to `\t`;
   - since `routine.arguments` doesn't have `type_` attribute, it was changed to `data_type`.
>         for argument in routine.arguments:
>             print("\t\tName: '{}'".format(argument.name))
>             print("\t\tType: '{}'".format(argument.type_))
>             AttributeError: 'RoutineArgument' object has no attribute 'type_'
4. **test_browse_table_data**:
   - add additional assertions (see point 1).
5. **test_load_table_dataframe**:
   - according to [pytest docs](http://doc.pytest.org/en/latest/reference.html#_pytest.outcomes.importorskip) `.importorskip` should be assigned to its canonical name (@tswast can you confirm these imports are required).
6. **test_get_dataset** and **test_list_datasets_by_label**:
   - exclude string formatting from the `assert`.
7. **test_routine_samples**:
   - divide into separate test files:
      - test_create_routine;
      - test_create_routine_ddl;
      - test_delete_routine;
      - test_get_routine (new file);
      - test_list_routines;
      - test_update_routine;

### CODE REVIEW

**Comment by Emar-Kar** [comment]
@plamut Yeah, I was surprised too. I saw these dots in several files that were already there. I need to know for sure, how @tswast would like to see `BigQuery` samples, to unify the design of all files. I appreciate your review.

**Comment by tswast** [comment]
The dots are probably because our internal samples style requires that all comments be complete sentences, with capital letters and punctuation. Accordingly, these comments should be changed to "Make an API request." or "The following function makes an API request."

**Comment by plamut** [comment]
@Emar-Kar I presume you just rebased, correct, no other changes?

If this was to fix the commit message lint check, I changed the PR title to make the bot happy.

**Comment by Emar-Kar** [comment]
@plamut yeah, I changed the comment lines and got this confusing error. New day = new features. Just read all about it. Thank you!

**Comment by plamut** [comment]
The Recommender failure is probably flakiness, I saw it on one of the other PRs, too (a re-run helped).

**Pull request merged**
