### PR TITLE
fix(vision): update a couple expected messages to fix broken vision vpc sc tests

### PR DESCRIPTION
**Pull request by brendanlundy**

### CODE REVIEW

**Comment by Emar-Kar** [comment]
Change your commit message as it is shown in the title now, please. See `conventionalcommits.org` [details](https://github.com/googleapis/google-cloud-python/pull/9640/checks?check_run_id=294201752).

**Comment by brendanlundy** [comment]
Updated commit message.

**Comment by busunkim96** [comment]
@brendanlundy I believe this will be resolved in #9620

**Comment by brendanlundy** [comment]
> @brendanlundy I believe this will be resolved in #9620

Yes, #9620 will fix it. We don't need my change.

**Comment by busunkim96** [comment]
Closing as #9620 has been merged.

**Pull request closed without merging**
