### PR TITLE
Add support for bucket retention policies

### PR DESCRIPTION
**Pull request by tseaver**
(Already reviewed in the private repo).

Merge is blocked pending public beta of the feature on the back-end.

@frankyn Please approve the PR once the back-end is ready.

### CODE REVIEW

**Comment by frankyn** [comment]
Thanks @tseaver!

**Comment by tseaver** [comment]
Rebased just now to synch with master.

**Comment by tseaver** [comment]
Rebased against current master.

**Comment by tseaver** [comment]
Fixing borked rebase now.

**Comment by frankyn** [comment]
@tseaver you can now merge and released. I don't have approval powers anymore.

**Pull request merged**
