### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by zenbanffy**
Small fix to formatting - a line that ended up formatted as code that shouldn't

### CODE REVIEW

**Comment by zenbanffy** [comment]
How do I sign a CLA?

**Comment by tseaver** [comment]
@zenbanffy 

> How do I sign a CLA?

The bot linked the page:

> Please visit https://cla.developers.google.com/ to sign.

**Comment by tseaver** [comment]
@crwilcox, @theacodes This is truly a "no copyright possible" change.

**Comment by zenbanffy** [comment]
I'm asking my manager if I can sign the corporate agreement, but I agree a copyright case would be very easy to shot down. It's my second smallest PR ever.

Are you the Tres Seaver I know from Zope?

**Comment by tseaver** [comment]
@zenbanffy 

> Are you the Tres Seaver I know from Zope?

Yup.

**Comment by crwilcox** [comment]
Thanks for finding this @zenbanffy. Unfortunately it is safer that all incoming PRs require a CLA, even if it is a space in a doc. :( That said, if you don't expect to ever contribute again, I can make this documentation modification as myself so you don't have to sign a CLA for a deletion of a space.

So, let me know how you would like to proceed. If you think you will want to contribute again to this or another google open source product it may be worth getting it out of the way now so next time it is faster.

**Comment by zenbanffy** [comment]
I'm pretty sure we'll need to fix the CLA thing eventually. I should have a definitive answer soon enough - I'll not be the first Zendeskian to go through this.

**Comment by zenbanffy** [comment]
I was added to the CLA group. Do I need to do anything else?

**Comment by crwilcox** [comment]
@zenbanffy If you reply with 'I signed it!' to this thread it ought to rescan.

**Comment by crwilcox** [comment]
@zenbanffy just checking in. If you can reply to this with "I signed it!" the bot should check the agreement and clear the CLA check.

**Comment by zenbanffy** [comment]
I signed it!

**Pull request merged**
