### PR TITLE
[Cloud Security Center]  Create requirements.txt

### PR DESCRIPTION
**Pull request by emkornfield**
[Cloud Security Center] Create requirements.txt

Adding a requirements.txt file to be linked from public documentation.

CC @tabrarian

### CODE REVIEW

**Comment by tseaver** [comment]
I don't understand the motivation for this change:  none of our other API libraries have `docs/requirements.txt` files.  There are two, `bigquery_datatransfer` and `bigquery_storage`, which have `samples/requirements.txt` files, used to populate the virtualenv which runs the samples.

**Comment by busunkim96** [comment]
+1 to @tseaver. Is there some other documentation gap that needs to be addressed?

**Comment by emkornfield** [comment]
@busunkim96 I CCed you the internal bug requesting this maybe you can way in there.

**Comment by busunkim96** [comment]
(Made a comment on the internal bug as well)

Since the samples live with the library the `requirements.txt` is not necessary. But to make this library more like the others with samples, let's move them to their own directory `samples/`.

**Pull request closed without merging**
