### PR TITLE
Firestore : add emulator support

### PR DESCRIPTION
**Pull request by HemangChothani**
Fixes:  #7500

### CODE REVIEW

**Comment by crwilcox** [comment]
Have we validated our tests pass against the emulator?

**Comment by HemangChothani** [comment]
The Doc testing requires modifications to be made to `environment_vars.py` file found in the Core library; namely extending the emulator variable declarations by another variable. During the test, however, the core library gets overwritten through pip install, losing the changes made to `environment_vars.py` and hence the newly added variable, which results in the doc test failure.

**Comment by tseaver** [comment]
The failed system test is due to #7130.

@HemangChothani To fix the docs build, you could update `firestore/noxfile.py` to install the "local dependencies", inside the `docs` session, e.g.:

```python
    for local_dep in LOCAL_DEPS:
        session.install("-e", local_dep
```

**Comment by tseaver** [comment]
@HemangChothani 

I don't see a response to the question @crwilcox asked:

> Have we validated our tests pass against the emulator?

**Comment by crwilcox** [comment]
@HemangChothani I am closing this because I ended up implementing this PR #8721 and forgot you had started on this. There are 4 open bugs internally against the emulator for small differences I found when running the tests against the emulator

**Pull request closed without merging**
