### PR TITLE
Videointelligence: Add v1p2beta1 to synth.py

### PR DESCRIPTION
**Pull request by danoscarmike**

### CODE REVIEW

**Comment by tseaver** [comment]
@danoscarmike I rebased to clear up CI.  Don't we need to re-run `synth.py` to pick up the new tree?

**Comment by danoscarmike** [comment]
@tseaver, thanks and yes, but wanted to get someone's eyes on it first (after my botched attempt to help on Redis 👎)

**Comment by danoscarmike** [comment]
LGTM - thanks @tseaver 

@theacodes to flip CLA label to `yes`.

**Comment by tseaver** [comment]
After rebasing to fix up master docs builds, Sphinx blows now:

```python
sphinx.errors.SphinxWarning: /home/tseaver/projects/agendaless/Google/src/google-cloud-python/docs/videointelligence/gapic/v1p2beta1/api.rst:document isn't included in any toctree
```

We need to land PR #6002, and then fix up `docs/index.rst` to include the v1p2beta1 API docs.

**Pull request merged**
