### PR TITLE
Adding Kokoro configuration for `ndb`.

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by tseaver** [comment]
I don't know what server-side configuration might be needed to enable the 'Kokoro - ndb' builds.  I guess @busunkim96, @crwilcox, or @theacodes have the keys.

**Comment by busunkim96** [comment]
I'll add the configurations server-side.

**Comment by dhermes** [comment]
Thanks @busunkim96. Should I wait to merge this until it's done?

**Comment by theacodes** [comment]
Should happen in roughly 5 minutes. Add kokoro:force-run to test.

**Pull request merged**
