### PR TITLE
feat(bigquery): add support for custom QueryJobConfig in BigQuery.cursor.execute method

### PR DESCRIPTION
**Pull request by TobKed**
My change allows to support `use_legacy_sql`.

### CODE REVIEW

**Comment by TobKed** [comment]
Thanks for feedback @plamut . I've applied changes suggested by you however still waiting for Kokoro check.

**Comment by TobKed** [comment]
**Kokoro - Recommender** check has failed however logs are empty. @plamut do you know maybe why it failed? I have no clue what is the reason.

**Comment by plamut** [comment]
@TobKed Seems like flakiness, saw the same on a few other PRs as well. I will try restarting the jobs.

**Comment by TobKed** [comment]
@plamut thanks for feedback! Good luck with fixing **Kokoro** :)

**Pull request merged**
