### PR TITLE
Storage: Add benchwrapper, support STORAGE_EMULATOR_HOST.

### PR DESCRIPTION
**Pull request by jadekler**

### CODE REVIEW

**Comment by tseaver** [comment]
@jadekler I've pushed the DRY changes to your branch.

**Comment by jadekler** [comment]
@googlebot I consent

**Comment by jadekler** [comment]
> @jadekler I've pushed the DRY changes to your branch.

Thank you!!

**Comment by jadekler** [comment]
(could somebody merge? I don't have powers to :) )

**Comment by jadekler** [comment]
@googlebot I consent.

**Comment by tseaver** [comment]
@googlebot I consent.

**Pull request merged**
