### PR TITLE
Storage: Make signurl work with objects containing tildes.

### PR DESCRIPTION
**Pull request by MewX**
Fixes https://issuetracker.google.com/issues/133359302

Similar to this one: https://github.com/GoogleCloudPlatform/gsutil/pull/783

### CODE REVIEW

**Comment by busunkim96** [comment]
Passing this along to the storage team. Would it be worth adding a unit test to test this case? @crwilcox @frankyn

**Comment by tseaver** [comment]
This PR breaks existing unit tests which assert that a slash in the blob name is *not* escaped, e.g.:  

```python
__________________ Test_Blob.test_public_url_w_slash_in_name ___________________
self = <tests.unit.test_blob.Test_Blob testMethod=test_public_url_w_slash_in_name>
    def test_public_url_w_slash_in_name(self):
        BLOB_NAME = "parent/child"
        bucket = _Bucket()
        blob = self._make_one(BLOB_NAME, bucket=bucket)
        self.assertEqual(
>           blob.public_url, "https://storage.googleapis.com/name/parent/child"
        )
E       AssertionError: 'https://storage.googleapis.com/name/parent%2Fchild' != 'https://storage.googleapis.com/name/parent/child'
E       - https://storage.googleapis.com/name/parent%2Fchild
E       ?                                           ^^^
E       + https://storage.googleapis.com/name/parent/child
E       ?                                           ^
tests/unit/test_blob.py:344: AssertionError
```

which would re-open #3809 (fixed in #4716).

**Comment by frankyn** [comment]
Hi @MewX, could you add "/" as a safe character as well? gsutil also does this at https://github.com/GoogleCloudPlatform/gsutil/pull/783/files#diff-2203ca5e293c09b69dae32ab51ee067aR543

**Comment by MewX** [comment]
Hi @frankyn, I have reverted my change to 0d4d991 which included `/` as a safe character.

However, that commit encountered a test failure:

```
Infrastructure error. Please apply label 'kokoro:force-run' to rerun the build.
```

**Comment by busunkim96** [comment]
Hi @MewX, that's our CI being flaky. I've re-triggered the tests.

**Comment by MewX** [comment]
Hi @busunkim96, the test failed again with the same error message. Would you like to take a look at the issue?

**Comment by tseaver** [comment]
The [Core Kokoro job](https://source.cloud.google.com/results/invocations/682ed794-477b-45da-8612-bdaf866fc03f) fails due to a Kokoro-internal glitch.

**Comment by MewX** [comment]
Hi @tseaver, could you or anyone please take a look at this bug fix? 

A customer might be waiting for this bug fix.

**Comment by frankyn** [comment]
@MewX rerunning tests.

**Comment by frankyn** [comment]
@tseaver @crwilcox the test has ran for 3 hours and hasn't completed. Is this normal for Storage IT?

**Comment by busunkim96** [comment]
@frankyn No idea if that's normal or not, but I'll just kicked off the storage job manually.

**Comment by tseaver** [comment]
@MewX I've just pushed PR #8434, which adds explicit unit test coverage for all the cases where `_quote` is used.  In order to make them all pass, I had to add the `safe` parameter to it:  anything where the URL is passed to the JSON API *must* percent quote `/`, but anything touching the XML API should not.

**Pull request closed without merging**
